### ISSUE TITLE
MDN Dev Tool missing after jpm run

### ISSUE THREAD

**Issue by groovecoder** [mozilla/mdn-devtool#11]
Steps to reproduce:
Follow README up thru `jpm run --binary /Applications/FirefoxDeveloperEdition.app/`

Expected Results:
Firefox Developer Edition opens with MDN in the dev tools.

Actual Results:
The MDN dev tool is missing. :frowning: 
![fdev-mdn-addon-missing](https://cloud.githubusercontent.com/assets/71928/6371938/09070c3e-bcc6-11e4-80ef-0a7716bab473.png)

Notes:
This happened to me with [another add-on](https://github.com/codesy/chrome-extension/pull/68) and `jpm` ... is there some kind of Firefox setting needed to make jpm run smoothly?

**Comment by darkwing** [comment]
Try installing JPM at version 0.0.23 -- that should fix this issue.

**Comment by darkwing** [comment]
Also, please let me know what error(s) you see in the shell.  Thank you!
